[project]
name = "api"
version = "0.1.0"
description = "API for kishandata.in"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.2",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "requests>=2.32.5",
    "uvicorn>=0.35.0",
]
